### ISSUE TITLE
Congratulation & Recommendation

### ISSUE THREAD

**Issue by rubbish-and-world** [LeafLight/LeafLight.github.io#1]
### Congratulate on your starting of blog 👍

*Blogging is a lonely journey*

* It is a good place to post all your stuff, you can put everything you want on the website. Your learning notes, your paintings, your codes, your feelings are all fantastic things to share ---- with yourself, maybe the whole world of course.
*  You may also be wondering why "waste" time doing such kinds of things, why not do a more attractive vlog, why not learn some more promising skills, why keep writing these no-one-read articles ...... And that's the question of choice, we have no time to waste, we have so much time to waste, right?

### Suggestions

*As we all know, it is important to select the right tool for your job, so I am here to give you some very **subjective** suggestions*

* Hexo may be a good choice if you want to spend more time writing articles rather than learning the [static site generators](https://jamstack.org/generators/)
  * It is simple, easy and beginner-friendly
  * However, you may think it is somehow not so splendid and want to have an interesting appearance, [cofincup's blog](https://cofincup.github.io/) can be a good example of using a theme.
  * As a tech guy, you will definitely want to do some custom modification to your site and Hexo is not a good choice if you'd like to dig deeper
    * the documentation is very limited
    * > Unless you have a good amount of experience with JavaScript or are willing to spend a lot of time learning, I would not recommend using Hexo for your blog. You will have to read and understand a lot of the code in order to make changes. I found it quite confusing. [origin](https://jr0cket.co.uk/hexo/hexo-theme-simple-changes.html)

* Hugo might be another candidate.
* Ghost seems to be suitable for commercial purposes.
* You can even [write your own](https://blog.hamaluik.ca/posts/build-your-own-static-site-generator/)

*Good luck.🍀*

**Comment by LeafLight** [comment]
# Thanks & Useless chatting &PLAN
Thanks for your suggestion. It's very useful and your _Issue_ is a nice example which shows me the advantages of the _markdown_
## Reasons for Starting the Github Blog 👨‍💻
Recently, I find that the _favourate_ of the _chrome_ is not as convinient as it seems to be.So I want to use javascript to create a _favourate fold page_ of my own. It comes to me that _Github_ may help because your share of your blog. Your recommendation of it before is quite useful.

## Waiting for the meeting and some __PLAN__ ✨
There are so many wonderful things for me to study and lean. I am waiting for the day we meet, maybe in the __ArKnight Winter Coffee Shop__ at  NJ.

if you are still willing, there are things we need to plan and take care of.
* determine __the day__ we go there
* remember to __reserve__ early,here is the name of the __wechat public account__ --"艾漫"(I will share the link to your wechat)
* there are only __44__ remains(but it seems like to be 44 forever, you will understant later)
* [an experience&suggestions blog of a enthusiastic _doctor_ ](https://www.bilibili.com/read/cv14048435)

_good luck!_.🍀

**Comment by LeafLight** [comment]
> ### Congratulate on your starting of blog 👍
> _Blogging is a lonely journey_
> 
> * It is a good place to post all your stuff, you can put everything you want on the website. Your learning notes, your paintings, your codes, your feelings are all fantastic things to share ---- with yourself, maybe the whole world of course.
> * You may also be wondering why "waste" time doing such kinds of things, why not do a more attractive vlog, why not learn some more promising skills, why keep writing these no-one-read articles ...... And that's the question of choice, we have no time to waste, we have so much time to waste, right?
> 
> ### Suggestions
> _As we all know, it is important to select the right tool for your job, so I am here to give you some very **subjective** suggestions_
> 
> * Hexo may be a good choice if you want to spend more time writing articles rather than learning the [static site generators](https://jamstack.org/generators/)
>   
>   * It is simple, easy and beginner-friendly
>   * However, you may think it is somehow not so splendid and want to have an interesting appearance, [cofincup's blog](https://cofincup.github.io/) can be a good example of using a theme.
>   * As a tech guy, you will definitely want to do some custom modification to your site and Hexo is not a good choice if you'd like to dig deeper
>     
>     * the documentation is very limited
>     * > Unless you have a good amount of experience with JavaScript or are willing to spend a lot of time learning, I would not recommend using Hexo for your blog. You will have to read and understand a lot of the code in order to make changes. I found it quite confusing. [origin](https://jr0cket.co.uk/hexo/hexo-theme-simple-changes.html)
> * Hugo might be another candidate.
> * Ghost seems to be suitable for commercial purposes.
> * You can even [write your own](https://blog.hamaluik.ca/posts/build-your-own-static-site-generator/)
> 
> _Good luck.🍀_

# Thanks & Useless chatting &PLAN
Thanks for your suggestion. It's very useful and your _Issue_ is a nice example which shows me the advantages of the _markdown_
## Reasons for Starting the Github Blog 👨‍💻
Recently, I find that the _favourate_ of the _chrome_ is not as convinient as it seems to be.So I want to use javascript to create a _favourate fold page_ of my own. It comes to me that _Github_ may help because your share of your blog. Your recommendation of it before is quite useful.

## Waiting for the meeting and some __PLAN__ ✨
There are so many wonderful things for me to study and lean. I am waiting for the day we meet, maybe in the __ArKnight Winter Coffee Shop__ at  NJ.

if you are still willing, there are things we need to plan and take care of.
* determine __the day__ we go there
* remember to __reserve__ early,here is the name of the __wechat public account__ --"艾漫"(I will share the link to your wechat)
* there are only __44__ remains(but it seems like to be 44 forever, you will understant later)
* [an experience&suggestions blog of a enthusiastic _doctor_ ](https://www.bilibili.com/read/cv14048435)

_good luck!_.🍀
